version: '3' # Specify version of compose to be used
services: # Each subkey creates a Docker container (i.e. service)
  blogging: # Each subkey are put into docker build and docker run
    build: . # Looks for a Dockerfile in the current dir and build that
    ports:
      - "8000:5000"
    environment:
      FLASK_APP: "blogging.py"
      FLASK_CONFIG: "docker"
      DATABASE_URL: "mysql+pymysql://someuser:somepassword@mysql-server/blogging"
    links: # This links subkey ensures mysql will start first before the blogging app
      - mysql:mysql-server
    restart: always
    image: aldosebastian/smallblog
    container_name: blogging_service
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "blogging"
      MYSQL_USER: "someuser"
      MYSQL_PASSWORD: "somepassword"
    restart: always
    ports:
      - "5423:3306"
    volumes:
      - /home/someuser/blogsDB/data:/var/lib/mysql # Use persisted data in this volume. Make sure the server has this folder.
    container_name: blogging_service_db
  